version: "3.8"
services:
  main:
    build: ./main
    container_name: microfrontend_customer_main
    ports:
      - 3000:3000
    networks:
      - dev_network

  domains:
    build: ./domains
    container_name: microfrontend_customer_domains
    ports:
      - 3001:3001
    networks:
      - dev_network

  auth:
    build: ./auth
    container_name: microfrontend_customer_auth
    ports:
      - 3002:3002
    networks:
      - dev_network

  store:
    build: ./store
    container_name: microfrontend_customer_store
    ports:
      - 3030:3030
    networks:
      - dev_network
 
  email:
    build: ./email
    container_name: microfrontend_customer_email
    ports:
      - 3003:3003
    networks:
      - dev_network
  
  settings:
    build: ./settings
    container_name: microfrontend_customer_settings
    ports:
      - 3006:3006
    networks:
      - dev_network

  payments:
    build: ./payments
    container_name: microfrontend_customer_payments
    ports:
      - 3007:3007
    networks:
      - dev_network
      
  billinghistory:
    build: ./billinghistory
    container_name: microfrontend_customer_billinghistory
    ports:
      - 3010:3010
    networks:
      - dev_network
 
networks:
  dev_network:
    driver: bridge
