# Use node alpine as it's a small node image
FROM node:18-alpine

# Create the directory on the node image 
# where our Next.js app will live
RUN mkdir -p /billinghistory

# Set /billinghistory as the working directory
WORKDIR /billinghistory

# Install git and other required tools
RUN apk add --no-cache git python3 make g++

# Copy package.json and package-lock.json to the working directory
COPY package*.json /billinghistory

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /billinghistory

# Expose port 3010
EXPOSE 3010

# Run the application
CMD ["npm", "run", "start"]
