apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  BASE_URL: "https://auth.customer.gworkspace.withhordanso.com"
  STORE_BASE_URL: "https://store.customer.gworkspace.withhordanso.com"