apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-domain-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-domain-service
  template:
    metadata:
      labels:
        app: frontend-domain-service
    spec:
      containers:
      - name: frontend-domain-service
        image: hordansodevops/reseller_customer_frontend_domain:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1.5"
            memory: "1Gi"
          requests:
            cpu: "0.75"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 300
          periodSeconds: 3
