apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-config
data:
  BASE_URL: "https://settings.customer.gworkspace.withhordanso.com"
  STORE_BASE_URL: "https://store.customer.gworkspace.withhordanso.com"