apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-store-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-store-service
  template:
    metadata:
      labels:
        app: frontend-store-service
    spec:
      containers:
      - name: frontend-store-service
        image: hordansodevops/reseller_customer_frontend_store:latest
        ports:
        - containerPort: 3030
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: store-config
