name: CI for API Service
   
on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:

env:
  DOCKER_IMAGE: hordansodevops/reseller_customer_frontend_api

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Debug Docker images on Hub
        run: |
          docker pull ${DOCKER_IMAGE}:${{ github.sha }} || echo "No image found on Docker Hub"


      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.0"

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
    
      - name: Apply Shared ConfigMap
        run: |
          kubectl apply -f k8s/api-configmap.yaml

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v3
        with:
          action: deploy
          strategy: basic
          manifests: |
            k8s/api-deployment.yaml
            k8s/api-service.yaml
          images: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
